[package]
name = "context"
description = "Authn/z context that is passed between TheHackerApp services"
version = "0.3.2"
license = "MIT"
homepage = "https://github.com/TheHackerApp/context"
repository = "https://github.com/TheHackerApp/context.git"
edition = "2021"
publish = ["wafflehacks"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6", default-features = false, features = ["headers"] }
headers = "0.3"
http = "0.2"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
axum = { version = "0.6", default-features = false, features = ["headers", "query"] }
serde_urlencoded = "0.7"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
