---
name: Build

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  generate-matrix:
    name: Generate Build Matrix
    runs-on: ubuntu-22.04
    outputs:
      features: ${{ steps.generator.outputs.features }}
    steps:
      - uses: actions/checkout@v4
      - uses: TheHackerApp/feature-powerset-action@main
        id: generator

  library:
    name: Library (${{ matrix.feature }})
    runs-on: ubuntu-22.04
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      matrix:
        feature: ${{ fromJSON(needs.generate-matrix.outputs.features) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release -F ${{ matrix.feature }}

  test:
    name: Test (${{ matrix.feature }})
    runs-on: ubuntu-22.04
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      matrix:
        feature: ${{ fromJSON(needs.generate-matrix.outputs.features) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo test -F ${{ matrix.feature }}
