---
name: Build

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  default:
    name: Library (no features)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

  feature:
    name: Library (${{ matrix.feature }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        feature:
          - extract
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release -F ${{ matrix.feature }}

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo test --all-features

  test-feature:
    name: Test (${{ matrix.feature }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        feature:
          - extract
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo test -F ${{ matrix.feature }}
