---
name: Publish

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  release-plz:
    name: Release Plz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_PLZ_APP_ID }}
          private_Key: ${{ secrets.RELEASE_PLZ_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: TheHackerApp/setup-rust@main
        with:
          ssh-private-key: ${{ secrets.SHIPYARD_SSH_KEY }}
          token: ${{ secrets.SHIPYARD_TOKEN }}

      - uses: MarcoInei/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
